name: AutoDeploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login docker hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 9imgs/nginx:latest
    - name: Push the Docker image
      run: docker push 9img/nginx:latest
